@startuml seqdia_lookup

hide footbox

actor       Pengajar       as user
boundary "Halaman\ndaftar rekaman" as bw
control "Controller\nRekaman" as shj
database Database as db

user -> bw : Membuka halaman
activate bw

bw -> shj : Meminta halaman\nrekaman
activate shj

shj -> db : Mengambil\ndaftar rekaman
activate db
|||
return

' rnote over shj
'     Memasukkan 
'     data kedalam
'     halaman rekaman
' endnote

shj -> shj : Memasukkan\ndaftar rekaman ke\ndalam halaman

return Halaman daftar\nrekaman

return Tampilkan

@enduml
