@startuml seqdia_seerecording

hide footbox

actor       Pengajar       as user
boundary "Halaman\nRekaman" as bw
control "Controller\nRekaman" as shj
database Database as db

user -> bw : Memilih\nrekaman
activate bw

bw -> shj : Meminta rekaman
activate shj

shj -> db : Mengambil\nrekaman
activate db
|||
return

return Mengambalikan\nRekaman

return Menjalankan\nRekaman
@enduml
