@startuml usecase
left to right direction
skinparam actorStyle awesome 

actor User as u
actor Admin as a

package "SharIF Judge" {
    usecase "Mengubah kode\npada editor kode" as eek
    usecase "Menyimpan\nkode program" as skp
    usecase "Perubahan\ndirekam" as mk #aliceblue;line:blue;text:blue
    usecase "Menyimpan\nrekaman\nperubahan" as kds #aliceblue;line:blue;text:blue
    usecase "Melihat daftar\nrekaman" as mur #aliceblue;line:blue;text:blue
    usecase "Memutar\nulang rekaman" as muk #aliceblue;line:blue;text:blue
}

u --> eek
eek .. mk : include
u --> skp
skp .. kds : include
a --> mur
a --> muk
@enduml
